# [Numpy](https://numpy.org)

NumPy è una libreria fondamentale per eseguire calcoli in Python. Fornisce diversi oggetti, tra cui vettori multidimensionali, e numerose operazioni eseguibili su tali vettori, come calcoli di statistica e algebra lineare.  

In Jupyter Notebook, è possibile utilizzare il punto esclamativo `!` per eseguire comandi come se stessimo usando il terminale. Per installare una libreria eseguiremo il comando `pip` (ovvero il package manager che vogliamo invocare) seguito da `install` e dal nome della libreria.

In [1]:
!pip install numpy


[notice] A new release of pip available: 22.1.2 -> 23.1.2
[notice] To update, run: pip install --upgrade pip


Il comando `import` ci permette di utilizzare una libreria all'interno del nostro programma. Utilizzando il comando `as` potremmo riferirci alla libreria che si sta importando con il nome che si sta definendo.

In [7]:
import numpy

In [4]:
numpy.array([0, 1])

array([0, 1])

In [9]:
import numpy as np

In [6]:
np.array([0, 1])

array([0, 1])

Un vettore N-dimensionale (`ndarray`) è un contenitore di elementi dello stesso tipo.

In [7]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [8]:
type(a)

numpy.ndarray

Il numero di dimensioni ed elementi in un vettore è definito dalla sua forma (`shape`), la quale è una tupla di N interi non-negativi che specifica la grandezza di ogni dimensione.

In [9]:
a.shape

(3,)

In [10]:
b = np.array([(1, 2, 3), (4, 5, 6)])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
type(b)

numpy.ndarray

In [11]:
b.shape

(2, 3)

In [12]:
a.dtype

dtype('int64')

In [13]:
c = np.array([1.2, 2.5, 7.8])
c

array([1.2, 2.5, 7.8])

In [14]:
type(c)

numpy.ndarray

In [16]:
c.dtype

dtype('float64')

In [18]:
d = np.array([0, 1, 2], dtype=float)

In [19]:
d

array([0., 1., 2.])

In [20]:
d.dtype

dtype('float64')

`numpy.zeros` restituisce un nuovo vettore avente una certa forma e tipo, con tutti gli elementi uguali a zero.

In [21]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

`numpy.ones` restituisce un nuovo vettore avente una certa forma e tipo, con tutti gli elementi uguali a uno.

In [22]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

`numpy.empty` restituisce un nuovo vettore avente una certa forma e tipo, senza inizializzare gli elementi.

In [24]:
np.empty((4, 1))

array([[0.],
       [0.],
       [0.],
       [0.]])

In [ ]:
# 0d: 1, scalare
# 1d: (1, 2, 3), vettore
# 2d: ([1, 2][3, 4]), matrice
# 3d+: tensore

In [26]:
t = np.ones((2, 3, 4))
t

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

Gli oggetti di tipo `ndarray` possono essere indicizzati con la sintassi standard di Python, ovvero `x[obj]`.

In [28]:
c

array([1.2, 2.5, 7.8])

In [27]:
c[0]

1.2

In [29]:
c[1:]

array([2.5, 7.8])

In [30]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
b[0]

array([1, 2, 3])

In [32]:
b[1]

array([4, 5, 6])

In [34]:
b[0][1]

2

In [35]:
b[0, 1]

2

Si ha un'indicizzazione avanzata quando l'oggetto che seleziona, `obj`, è una sequenza.

In [38]:
c

array([1.2, 2.5, 7.8])

In [39]:
c[[0, 0, 1, 0]]

array([1.2, 1.2, 2.5, 1.2])

In [40]:
l = [1.2, 2.5, 7.8]

In [41]:
l[1:]

[2.5, 7.8]

In [42]:
l[0]

1.2

In [43]:
l[[0, 0, 1, 0]]

TypeError: list indices must be integers or slices, not list

In [44]:
x = np.array([20, 30, 40, 50])
x

array([20, 30, 40, 50])

In [45]:
x > 35

array([False, False,  True,  True])

In [46]:
x[x > 35]

array([40, 50])

In [47]:
x[[False, False,  True,  True]]

array([40, 50])

È possibile selezionare un sottoinsieme di un vettore ed assegnarlo utilizzando le tecniche di indicizzazione viste prima.

In [50]:
t

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [51]:
t[0, 0, 2] = 5
t

array([[[1., 1., 5., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

`numpy.arange` restituisce un vettore avente valori equidistanti.

In [54]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [55]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
list(range(0, 10, 2))

[0, 2, 4, 6, 8]

In [57]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

`numpy.linspace` restituisce un vettore avente un specifico numero di elementi equidistanti su un certo intervallo.

In [58]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [59]:
np.linspace(0, 8, 5)

array([0., 2., 4., 6., 8.])

In [62]:
np.linspace(0, 8, 5, endpoint=False)

array([0. , 1.6, 3.2, 4.8, 6.4])

In [60]:
np.linspace(0, 8, 7)

array([0.        , 1.33333333, 2.66666667, 4.        , 5.33333333,
       6.66666667, 8.        ])

In [61]:
np.ndarray((2, 2))

array([[2., 4.],
       [6., 8.]])

In [63]:
a

array([1, 2, 3])

In [65]:
c

array([1.2, 2.5, 7.8])

In [66]:
a + c

array([ 2.2,  4.5, 10.8])

In [68]:
list(a) + list(c)

[1, 2, 3, 1.2, 2.5, 7.8]

In [70]:
s = []
for i in range(len(a)):
    s.append(a[i] + c[i])

In [71]:
s

[2.2, 4.5, 10.8]

In [72]:
a * c

array([ 1.2,  5. , 23.4])

In [74]:
a - c

array([-0.2, -0.5, -4.8])

In [75]:
a - b

array([[ 0,  0,  0],
       [-3, -3, -3]])

In [76]:
a

array([1, 2, 3])

In [77]:
b

array([[1, 2, 3],
       [4, 5, 6]])

NumPy include diverse costanti, come `Inf` e `pi`.

In [78]:
np.pi

3.141592653589793

In [79]:
np.Inf

inf

In [80]:
type(np.Inf)

float

In [81]:
np.e

2.718281828459045

In [82]:
np.cos(0)

1.0

In [83]:
np.sin(0)

0.0

In [84]:
A = np.array([[1, 1], [0, 1]])

In [85]:
A

array([[1, 1],
       [0, 1]])

In [86]:
B = np.array([[2, 0], [3, 4]])

In [87]:
B

array([[2, 0],
       [3, 4]])

In [88]:
A + B

array([[3, 1],
       [3, 5]])

In [89]:
A * B

array([[2, 0],
       [0, 4]])

In [90]:
A @ B

array([[5, 4],
       [3, 4]])

In [91]:
np.matmul(A, B)

array([[5, 4],
       [3, 4]])

In [92]:
np.dot(A, B)

array([[5, 4],
       [3, 4]])

In [94]:
np.dot(a, c)

29.599999999999998

In [95]:
np.min(c)

1.2

In [96]:
np.max(c)

7.8

In [97]:
np.mean(c)

3.8333333333333335

In [98]:
np.std(c)

2.854625875467552

In [99]:
np.var(c)

8.148888888888889

Il metodo `reshape` cambia la forma del vettore senza cambiare i dati contenuti in esso.

In [100]:
e = np.arange(12)
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [101]:
e.shape

(12,)

In [103]:
e = e.reshape(3, 4)
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [104]:
e.shape

(3, 4)

In [105]:
e.sum()

66

In [106]:
e.sum(axis=0)

array([12, 15, 18, 21])

In [107]:
e.sum(axis=1)

array([ 6, 22, 38])

In [109]:
e[0, 2]

2

In [113]:
e = e.reshape(-1)
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [114]:
e.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [115]:
len(e)

12

In [117]:
len(b[0])

3

`numpy.ravel` permette di 'appiattire' un vettore.

In [110]:
np.ravel(e)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [1]:
import random

In [ ]:
# 9, 4, 6, 7
# 6, 8, 2, ...

In [2]:
random.seed(123)

In [ ]:
# 0, 4, 1, 6, ...
# 0, 4, 1, 6, ...

In [6]:
random.randint(0, 10)

6

`numpy.random.normal` genera esempi da una distribuzione Gaussiana normale.

In [10]:
np.random.normal(0, 1, 10)

array([-0.94954674, -0.31931853,  1.51542955, -0.40777511, -0.60695842,
       -0.02219605,  0.72901797, -0.91404444, -0.40835451, -1.4514067 ])

In [11]:
mu = 0
sigma = 1

sample = np.random.normal(mu, sigma, 100)

In [14]:
sample.mean(), sample.std()

(-0.05168453723766959, 1.0648257688601521)

In [15]:
sample = np.random.normal(mu, sigma, 10000)
sample.mean(), sample.std()

(-0.002251903622663321, 1.0093733401830842)